### ISSUE TITLE
Documentation update - Vendor publish 

### ISSUE THREAD

**Issue by hfmiguel** [lacodix/laravel-model-filter#40]
Hi  , 

Im starting with your package and i get a little mistake in the documentation , with vendor publish hehe . 

php artisan vendor:publish --tag="laravel-model-filter-config" will be 
php artisan vendor:publish --tag="model-filter-config"

And 
php artisan vendor:publish --tag="lacodix-filter-translations" will be 
php artisan vendor:publish --tag="model-filter-translations"

**Comment by renky** [comment]
Hi

thanks for your comment, I just updated the docs...

I also added a new feature few days ago that also missed in the docs: hiding filters programmatically...
https://www.lacodix.de/docs/laravel-model-filter/v1/basic-usage/filter-visibility

just needed it in a own project where not all filters should always be visible decided by Laravel Penant

If you think there is something missing, or something not working as expected, please contact me again...
