### ISSUE TITLE
Filters not working

### ISSUE THREAD

**Issue by hfmiguel** [lacodix/laravel-model-filter#42]
Hi , 

Im trying to use filters and isnt work.

I try filter and search methods and only search works. I disable search but filter not work . 

At the printscreen below , we can see the result of search method and filter method. With filter, not insert the query to search for my column. 

So , what im doing wrong ? 

-- Notes:
- php 8.1
- Laravel 9.52.7
- Package version 1.8.3

### App\MyModel.php

![image](https://github.com/lacodix/laravel-model-filter/assets/14097051/307cbbba-625f-462f-a3a9-5900c6f51c26)

### CLI Test 

````
> 
> 
> Company::filter(['my_select_filter' => 1])->toSql()
= "select * from `companies`"

> Company::search('test')->toSql()
= "select * from `companies` where (`name` LIKE ?)"

> 
````

### My filter

```
class MySelectFilter extends SelectFilter
{
    public FilterMode $mode = FilterMode::EQUAL;

    protected string $field = 'my_column_id';

    public function title(): string
    {
        return __('Sector');
    }

    public function component(): string
    {
        return 'select';
    }

    public function options(): array
    {
        return OtherModel::query()
            ->orderBy('name')
            ->pluck('name', 'id')
            ->toArray();
    }
}
```

**Comment by renky** [comment]
It should work if you just turn around keys and values of your option array:

```
public function options(): array
    {
        return OtherModel::query()
            ->orderBy('name')
            ->pluck('id', 'name')
            ->toArray();
    }
```

The Filtersystem expects the allowed values for filtering in the value-part of the options-array.
The key (if it isn't a sequential array) is only used for filter-visualisation

This is a good hint for extending the documentation

**Comment by renky** [comment]
I updated the docs - but it will not be shown on the Documentation page until a new release is released:
you can view it here:
https://github.com/lacodix/laravel-model-filter/tree/master/docs/filter-types

**Comment by hfmiguel** [comment]
This not work hehe.

```
public function options(): array
    {
        return OtherModel::query()
            ->orderBy('name')
            ->pluck('id', 'name')
            ->toArray();
    }
```

The name attribute must be before ID ( pluck('name', 'id')  its the right way.

**Comment by hfmiguel** [comment]
> This not work hehe.
> 
> ```
> public function options(): array
>     {
>         return OtherModel::query()
>             ->orderBy('name')
>             ->pluck('id', 'name')
>             ->toArray();
>     }
> ```
> 
> The name attribute must be before ID ( pluck('name', 'id') its the right way.



Sorry , my mistake. 


im build my own component and  , using ('íd', 'name')  my select works wrong , but the filter works fine hehe. 


I write a custom function to parse the values of the array ( options ) property and work fine.

![image](https://github.com/lacodix/laravel-model-filter/assets/14097051/a063d60c-5431-48a8-aa90-afe1ee40b7a2)

![image](https://github.com/lacodix/laravel-model-filter/assets/14097051/790a3eef-7c4f-4f21-a87f-f9349f32dbc6)


So , now  , looks working fine . 

Thanks for the help.

**Comment by hfmiguel** [comment]
My suggestion , 

Put to work with  **pluck('name'or title, wte , 'id')**  ( filter not work ) 

because the output array will be :

[
   1 => 'name'
]

Using this way ( filter work ) **pluck('id''name')**, the output will be 

[
'name' => 1
]

Using translatable package , will be: 

[
'{en: name}' => 1
]


In my project  , i use laravel Translatable , so  , using **pluck('id''name')** laravel parse the right translation to my model and i can render properly the select with the options . 


So , i can parse and mount my array , but the translations wasnt parsed.

**Comment by hfmiguel** [comment]
> My suggestion ,
> 
> Put to work with **pluck('name'or title, wte , 'id')** ( filter not work )
> 
> because the output array will be :
> 
> [ 1 => 'name' ]
> 
> Using this way ( filter work ) **pluck('id''name')**, the output will be
> 
> [ 'name' => 1 ]
> 
> Using translatable package , will be:
> 
> [ '{en: name}' => 1 ]
> 
> In my project , i use laravel Translatable , so , using **pluck('id''name')** laravel parse the right translation to my model and i can render properly the select with the options .
> 
> So , i can parse and mount my array , but the translations wasnt parsed.



Update. 

This way works fine with Translatable. If has translation ,fetch the right item from translate ,if not, use the value.

![image](https://github.com/lacodix/laravel-model-filter/assets/14097051/06f3f9ba-6a85-43c8-b02a-d490f6dcb081)

**Comment by renky** [comment]
To be honest - I'm a bit confused now... :-)

Why do you need this huge availableFilters-Array? Or is it just for some caching-purpose?

About the "filterIsActive" functionality: I already thought about adding such a thing, but finaly I came to the solution that this isn't scope of the package... In an application where I used it, i added a macro "isActive" to the filters (all Filters ar macroable) and just checked if the query-parameter is set for the filter, and returning true) - so I always work with the filter-objects itself...

about your translation problem: what about not using pluck on database? pluck is only a convenient way to fetch only the needed data from database, but you can also do this::

```
public function options(): array
    {
        return OtherModel::query()
            ->get()
            ->mapWithKeys(fn ($otherModel) => [$otherModel->name => $otherModel->id])
            ->toArray();
    }
```
I guess accessing name over the model will give you the translated string.

and even sort it:
```
public function options(): array
    {
        return OtherModel::query()
            ->get()
            ->mapWithKeys(fn ($otherModel) => [$otherModel->name => $otherModel->id])
            ->sortKeys()
            ->toArray();
    }
```

**Comment by hfmiguel** [comment]
Hi , 

Im write a FilterBarComponent  , that receive the model and render the filters ,  make filter active or disable it . 

About the mapWithKeys method, works fine   , im me select component  , i change the key by values and now looks good.
