### ISSUE TITLE
Filters omit all falsy values

### ISSUE THREAD

**Issue by rikumtub** [lacodix/laravel-model-filter#52]
Hi,

This function in the `HasFilters` trait filters out all falsy values, including `0`, `'0'` and `false`:

```
protected function getOnlyFilterUsableValues(array $values, string $group): Collection
{
    return collect($values)
        ->only($this->getAllFilterQueryNames($group))
        ->filter();
}
```

As a consequence, a `NumberFilter` with a single value mode won't work when passed `0` as a value.

The filter function should only omit nulls and empty strings:

```
protected function getOnlyFilterUsableValues(array $values, string $group): Collection
{
    return collect($values)
        ->only($this->getAllFilterQueryNames($group))
        ->filter(fn ($value) => isset($value) && $value !== '');
}
```

**Comment by renky** [comment]
fixed in [1.9.4](https://github.com/lacodix/laravel-model-filter/releases/tag/v1.9.4)
