### ISSUE TITLE
Typo in sorting documentation page

### ISSUE THREAD

**Issue by vstruhar** [lacodix/laravel-model-filter#55]
I did a copy paste of method name from docs and it wasn't working, later found out that the method name is not correct in the docs. 
And thanks for the package, it's awesome!

![image](https://github.com/lacodix/laravel-model-filter/assets/6599021/7144e306-7cb3-40c3-bb4c-46cfbce9f578)
Here is the link: https://www.lacodix.de/docs/laravel-model-filter/v1/basic-usage/sort

**Comment by renky** [comment]
sorry for the long time to wait 

I just released a new Version that also contains default sorting and I updated the docs - also thanks to @bearcodi 

https://www.lacodix.de/docs/laravel-model-filter/v1/basic-usage/sort#content-default-sorting
